-- GRM Wanted client v2.0
if not CLIENT then return end
include("autorun/sh_grm_wanted_config.lua");GRM=GRM or{};GRM.Wanted=GRM.Wanted or{};local W=GRM.Wanted
local OPEN,DATA,ACT,SYNC,INFO,DETAIL="GRM_Wanted_Open","GRM_Wanted_Data","GRM_Wanted_Act","GRM_Wanted_Sync","GRM_Wanted_Info","GRM_Wanted_List"
local UI={bg=Color(11,16,24,252),head=Color(21,29,42),panel=Color(27,38,53),card=Color(34,47,64),text=Color(238,244,250),dim=Color(151,169,190),blue=Color(65,145,240),green=Color(62,190,118),red=Color(218,75,80),orange=Color(239,159,68),yellow=Color(239,199,82)}
surface.CreateFont("GRMW2_Title",{font="Roboto",size=23,weight=900,extended=true});surface.CreateFont("GRMW2_Head",{font="Roboto",size=16,weight=800,extended=true});surface.CreateFont("GRMW2_Body",{font="Roboto",size=13,weight=550,extended=true});surface.CreateFont("GRMW2_Small",{font="Roboto",size=11,weight=500,extended=true})
W.LocalLevel=W.LocalLevel or 0
local function money(n)return GRM.Format and GRM.Format(n)or tostring(n)end
local function btn(p,t,c)local b=vgui.Create("DButton",p);b:SetText(t);b:SetFont("GRMW2_Body");b:SetTextColor(color_white);b.Paint=function(self,w,h)local x=self:IsHovered()and Color(math.min(c.r+18,255),math.min(c.g+18,255),math.min(c.b+18,255))or c;draw.RoundedBox(6,0,0,w,h,x)end;return b end
local function act(t)net.Start(ACT)net.WriteTable(t)net.SendToServer();surface.PlaySound("buttons/button15.wav")end
local function targetPicker(p,players,y)
 local combo=vgui.Create("DComboBox",p);combo:SetPos(14,y);combo:SetSize(430,30);combo:SetValue("Игрок онлайн...");for _,x in ipairs(players)do combo:AddChoice(x.nick.." • ур."..x.level,x.sid64)end
 local manual=vgui.Create("DTextEntry",p);manual:SetPos(454,y);manual:SetSize(300,30);manual:SetPlaceholderText("CharacterKey / SteamID64")
 local function get()local _,id=combo:GetSelected();return(id and id~="")and id or string.Trim(manual:GetValue()or"")end;return get
end
local function open(canEdit,records,catalog,players,history,levels,maxLevel)
 if IsValid(W.Frame)then W.Frame:Remove()end;local f=vgui.Create("DFrame");W.Frame=f;GRM.UI.Track("wanted",f);f:SetSize(math.Clamp(ScrW()*.84,1120,1520),math.Clamp(ScrH()*.86,720,940));f:Center();f:MakePopup();f:SetTitle("");f:ShowCloseButton(false);f.Paint=function(_,w,h)draw.RoundedBox(10,0,0,w,h,UI.bg);draw.RoundedBoxEx(10,0,0,w,62,UI.head,true,true,false,false);draw.SimpleText("GRM / ЕДИНАЯ БАЗА РОЗЫСКА","GRMW2_Title",20,31,UI.text,TEXT_ALIGN_LEFT,TEXT_ALIGN_CENTER);draw.SimpleText(canEdit and"РЕДАКТИРОВАНИЕ"or"ТОЛЬКО ПРОСМОТР","GRMW2_Body",w-60,31,canEdit and UI.green or UI.dim,TEXT_ALIGN_RIGHT,TEXT_ALIGN_CENTER)end
 local close=btn(f,"×",UI.red);close:SetPos(f:GetWide()-44,15);close:SetSize(30,30);close.DoClick=function()f:Close()end;local tabs=vgui.Create("DPropertySheet",f);tabs:Dock(FILL);tabs:DockMargin(12,72,12,12)
 -- Records
 local cases=vgui.Create("DPanel");cases:SetPaintBackground(false);tabs:AddSheet("Дела и розыск",cases,"icon16/exclamation.png");local left=vgui.Create("DPanel",cases);left:Dock(LEFT);left:SetWide(470);left.Paint=function(_,w,h)draw.RoundedBox(7,0,0,w,h,UI.panel)end;local search=vgui.Create("DTextEntry",left);search:Dock(TOP);search:SetTall(30);search:DockMargin(7,7,7,4);search:SetPlaceholderText("Поиск по имени или ID...");local lv=vgui.Create("DListView",left);lv:Dock(FILL);lv:DockMargin(7,0,7,7);lv:AddColumn("Ур."):SetFixedWidth(40);lv:AddColumn("Гражданин");lv:AddColumn("Статей"):SetFixedWidth(55);lv:AddColumn("Штрафы"):SetFixedWidth(100)
 local function fill()lv:Clear();local q=string.lower(search:GetValue()or"");for _,r in ipairs(records)do if q==""or string.find(string.lower((r.name or"").." "..r.sid),q,1,true)then local line=lv:AddLine(r.level,r.name,r.reasons,money(r.totalFine or 0));line.sid=r.sid end end end;search.OnChange=fill;fill()
 local right=vgui.Create("DPanel",cases);right:Dock(FILL);right:DockMargin(8,0,0,0);right.Paint=function(_,w,h)draw.RoundedBox(7,0,0,w,h,UI.panel)end;local info=vgui.Create("DLabel",right);info:Dock(TOP);info:SetTall(55);info:DockMargin(10,8,10,3);info:SetFont("GRMW2_Body");info:SetTextColor(UI.text);info:SetWrap(true);info:SetText("Выберите дело слева")
 local charges=vgui.Create("DListView",right);charges:Dock(FILL);charges:DockMargin(8,2,8,6);charges:AddColumn("Код"):SetFixedWidth(75);charges:AddColumn("Статья");charges:AddColumn("Обстоятельства");charges:AddColumn("Тип"):SetFixedWidth(65);charges:AddColumn("Штраф"):SetFixedWidth(85);charges:AddColumn("Ур."):SetFixedWidth(35);charges:AddColumn("Кем"):SetFixedWidth(110)
 local selectedSid;lv.OnRowSelected=function(_,_,line)selectedSid=line.sid;act({action="get",sid=selectedSid})end
 net.Receive(DETAIL,function()local r=net.ReadTable()or{};charges:Clear();if not r.sid then return end;selectedSid=r.sid;info:SetText(("%s • уровень %d\n%s"):format(r.name or"?",r.level or 0,r.sid));for i,c in ipairs(r.reasons or{})do local line=charges:AddLine(c.code or c.id,c.title,c.text or"",c.type,money(c.fine or 0),c.level,c.byNick or"?");line.index=i end end)
 if canEdit then local bar=vgui.Create("DPanel",right);bar:Dock(BOTTOM);bar:SetTall(42);bar:SetPaintBackground(false);local clear=btn(bar,"Снять розыск",UI.green);clear:Dock(LEFT);clear:SetWide(150);clear:DockMargin(8,5,4,5);clear.DoClick=function()if selectedSid then act({action="clear",sid=selectedSid,text="Снято через UI"})end end;local remove=btn(bar,"Удалить статью",UI.orange);remove:Dock(LEFT);remove:SetWide(155);remove:DockMargin(4,5,4,5);remove.DoClick=function()local rows=charges:GetSelected();if selectedSid and rows[1]then act({action="remove_reason",sid=selectedSid,index=rows[1].index})end end end
 if canEdit then
  -- Assign
  local assign=vgui.Create("DPanel");assign:SetPaintBackground(false);tabs:AddSheet("Вменить статью",assign,"icon16/add.png");local getTarget=targetPicker(assign,players,14);local mode=vgui.Create("DPropertySheet",assign);mode:SetPos(14,58);mode:SetSize(assign:GetWide()-28,560);mode:Dock(FILL);mode:DockMargin(14,58,14,14)
  local fromCat=vgui.Create("DPanel");fromCat:SetPaintBackground(false);local ac=vgui.Create("DComboBox",fromCat);ac:SetPos(12,15);ac:SetSize(620,30);ac:SetValue("Выберите статью каталога...");for _,a in ipairs(catalog)do ac:AddChoice((a.code or a.id).." • "..a.title.." • ур."..a.defaultLevel.." • "..money(a.fine),a.id)end;local note=vgui.Create("DTextEntry",fromCat);note:SetPos(12,58);note:SetSize(620,30);note:SetPlaceholderText("Комментарий / обстоятельства");local level=vgui.Create("DNumberWang",fromCat);level:SetPos(645,15);level:SetSize(80,30);level:SetMin(0);level:SetMax(maxLevel);level:SetValue(0);local add=btn(fromCat,"ВМЕНИТЬ ИЗ КАТАЛОГА",UI.red);add:SetPos(12,104);add:SetSize(713,38);add.DoClick=function()local sid=getTarget();local _,id=ac:GetSelected();if sid~=""and id then act({action="add_charge",sid=sid,article=id,text=note:GetValue(),level=level:GetValue()})end end;mode:AddSheet("Из каталога",fromCat,"icon16/book.png")
  local custom=vgui.Create("DPanel");custom:SetPaintBackground(false);local function field(ph,x,y,w)local e=vgui.Create("DTextEntry",custom);e:SetPos(x,y);e:SetSize(w,30);e:SetPlaceholderText(ph);return e end;local code=field("Номер / код статьи",12,15,180);local title=field("Название статьи вручную",202,15,430);local text=field("Описание обстоятельств",12,58,620);local typeBox=vgui.Create("DComboBox",custom);typeBox:SetPos(645,15);typeBox:SetSize(140,30);typeBox:AddChoice("Уголовная","crime",true);typeBox:AddChoice("Административная","admin");local fine=vgui.Create("DNumberWang",custom);fine:SetPos(645,58);fine:SetSize(140,30);fine:SetMin(0);fine:SetMax(100000000);fine:SetValue(0);local lvl=vgui.Create("DNumberWang",custom);lvl:SetPos(12,104);lvl:SetSize(90,30);lvl:SetMin(1);lvl:SetMax(maxLevel);lvl:SetValue(1);local addCustom=btn(custom,"ВМЕНИТЬ РУЧНУЮ СТАТЬЮ",UI.orange);addCustom:SetPos(115,104);addCustom:SetSize(670,38);addCustom.DoClick=function()local sid=getTarget();local _,typ=typeBox:GetSelected();if sid~=""then act({action="add_custom",sid=sid,code=code:GetValue(),title=title:GetValue(),text=text:GetValue(),type=typ or"crime",fine=fine:GetValue(),level=lvl:GetValue()})end end;mode:AddSheet("Ручная статья",custom,"icon16/pencil.png")
  -- Catalog editor
  if LocalPlayer():IsSuperAdmin()then local cp=vgui.Create("DPanel");cp:SetPaintBackground(false);local list=vgui.Create("DListView",cp);list:Dock(LEFT);list:SetWide(560);list:AddColumn("Код"):SetFixedWidth(85);list:AddColumn("Название");list:AddColumn("Ур."):SetFixedWidth(40);list:AddColumn("Штраф"):SetFixedWidth(90);local work=table.Copy(catalog);local function refill()list:Clear();for i,a in ipairs(work)do local l=list:AddLine(a.code or a.id,a.title,a.defaultLevel,money(a.fine));l.index=i end end;refill();local form=vgui.Create("DPanel",cp);form:Dock(FILL);form:DockMargin(8,0,0,0);form:SetPaintBackground(false);local c=field -- dummy avoidance
   local function fe(ph,y)local e=vgui.Create("DTextEntry",form);e:SetPos(8,y);e:SetSize(390,28);e:SetPlaceholderText(ph);return e end;local id=fe("ID латиницей",8);local cd=fe("Код статьи",42);local ti=fe("Название",76);local ds=fe("Описание",110);local fi=vgui.Create("DNumberWang",form);fi:SetPos(8,146);fi:SetSize(180,28);fi:SetMin(0);fi:SetMax(100000000);local le=vgui.Create("DNumberWang",form);le:SetPos(198,146);le:SetSize(80,28);le:SetMin(1);le:SetMax(maxLevel);local addRow=btn(form,"Добавить / заменить",UI.green);addRow:SetPos(8,185);addRow:SetSize(270,32);addRow.DoClick=function()local row={id=id:GetValue(),code=cd:GetValue(),title=ti:GetValue(),description=ds:GetValue(),fine=fi:GetValue(),defaultLevel=le:GetValue(),type="crime"};work[#work+1]=row;refill()end;local del=btn(form,"Удалить выбранную",UI.red);del:SetPos(8,225);del:SetSize(270,32);del.DoClick=function()local s=list:GetSelected();if s[1]then table.remove(work,s[1].index);refill()end end;local save=btn(form,"СОХРАНИТЬ КАТАЛОГ",UI.blue);save:SetPos(8,275);save:SetSize(390,36);save.DoClick=function()act({action="save_catalog",catalog=work})end;tabs:AddSheet("Каталог статей",cp,"icon16/book_edit.png")end
 end
 -- History
 local hp=vgui.Create("DPanel");hp:SetPaintBackground(false);local hv=vgui.Create("DListView",hp);hv:Dock(FILL);hv:AddColumn("Время"):SetFixedWidth(140);hv:AddColumn("Сотрудник"):SetFixedWidth(150);hv:AddColumn("Событие");for i=#history,math.max(1,#history-199),-1 do local h=history[i];hv:AddLine(os.date("%d.%m.%Y %H:%M",h.t or os.time()),h.actorName or"Система",h.s or"")end;tabs:AddSheet("История",hp,"icon16/time.png")
end
net.Receive(DATA,function()open(net.ReadBool(),net.ReadTable()or{},net.ReadTable()or{},net.ReadTable()or{},net.ReadTable()or{},net.ReadTable()or{},net.ReadUInt(4))end)
net.Receive(SYNC,function()W.LocalLevel=net.ReadUInt(4);net.ReadString();hook.Run("GRM_WantedLevelChanged",W.LocalLevel)end)
net.Receive(INFO,function()notification.AddLegacy(net.ReadString(),NOTIFY_GENERIC,4)end)
function W.OpenMenu()net.Start(OPEN)net.SendToServer()end;concommand.Add("grm_wanted",W.OpenMenu)
hook.Add("HUDPaint","GRM_Wanted_BadgeV2",function()local l=tonumber(W.LocalLevel)or LocalPlayer():GetNW2Int("GRM_WantedLevel",0);if l<=0 then return end;local _,i=W.GetLevelInfo(l);local bx,by,bw,bh=16,136,150,26;draw.RoundedBox(6,bx,by,bw,bh,i.color);draw.SimpleText((i.short or"").." "..i.name,"GRMW2_Body",bx+bw/2,by+bh/2,Color(255,255,255),TEXT_ALIGN_CENTER,TEXT_ALIGN_CENTER)end)
print("[GRM Wanted] client v2.0 loaded")
