-- Contracts for designed, CharacterKey-safe faction invitation flow.
local function read(p)local f=assert(io.open(p,"rb"));local s=f:read("*a");f:close();return s end
local fac=read("lua/autorun/sh_factions.lua")
local fail,n=0,0;local function ok(v,msg)n=n+1;if v then print("  ok  "..msg)else fail=fail+1;print("  FAIL "..msg)end end
ok(fac:find('Factions_InviteOpenV2',1,true)and fac:find('Factions_InviteActionV2',1,true),"dedicated invite protocol exists")
ok(fac:find("local INVITE_LIFETIME=300",1,true),"invites expire after five minutes")
ok(fac:find("local function normalizeInvite",1,true)and fac:find("legacy_",1,true),"legacy invite records migrate in memory")
ok(fac:find("id=\"fi_\"..now",1,true),"each invitation has a nonce")
ok(fac:find("targetKey==fromKey",1,true),"self-invite is rejected")
ok(fac:find("уже есть активное приглашение",1,true),"parallel invite overwrite is rejected")
ok(fac:find("desiredRole==f.LeaderRoleName",1,true)and fac:find("Недопустимый стартовый отдел",1,true),"initial role and department are server validated")
ok(fac:find("role=desiredRole,department=desiredDepartment",1,true),"assignment is persisted with invite")
ok(fac:find("Role=inv.role",1,true)and fac:find("Department=inv.department",1,true),"accepted member receives promised assignment")
ok(fac:find('GRM.Net.Guard(ply,"factions.invite.action"',1,true),"decision receiver has network guard")
ok(fac:find("inv.id~=inviteID",1,true),"stale modal cannot accept replaced invite")
ok(fac:find("Factions_InviteV2Expire",1,true),"server sweeps expired invitations")
ok(fac:find("Factions_InviteV2Character",1,true)and fac:find("resendInvite(ply,true)",1,true),"modal follows active CharacterKey")
ok(fac:find("invite.sent",1,true)and fac:find("invite.accepted",1,true)and fac:find("invite.declined",1,true),"invite lifecycle is audited")
ok(fac:find("ОФИЦИАЛЬНОЕ ПРИГЛАШЕНИЕ",1,true)and fac:find("НАЗНАЧЕНИЕ ПОСЛЕ ВСТУПЛЕНИЯ",1,true),"large designed invitation modal exists")
ok(fac:find("Осталось: ",1,true)and fac:find("ОТКЛОНИТЬ",1,true)and fac:find("ПРИНЯТЬ",1,true),"modal shows countdown and explicit decisions")
ok(fac:find("confirmInvite",1,true)and fac:find("ПОДТВЕРЖДЕНИЕ ПРИГЛАШЕНИЯ",1,true),"leader/admin sees confirmation design")
ok(fac:find('sendAction("inviteMember",{faction,steam,role,dept}',1,true),"admin invitation transmits assignment")
ok(fac:find('sendAction("inviteMember",{steam,role,dept}',1,true),"leader invitation transmits assignment")
ok(fac:find('^/fjoin',1,true)and fac:find('^/fdecline',1,true),"legacy chat fallback remains")
print(("FACTION INVITES V2: %d/%d failures=%d"):format(n-fail,n,fail));os.exit(fail==0 and 0 or 1)
