--[[--------------------------------------------------------------------
    sim_fire — контракт Кода 58
    ./.luabuild/lj/src/luajit tools/luatest/sim_fire.lua
----------------------------------------------------------------------]]
local function read(p)
    local f = assert(io.open(p, "rb"))
    local s = f:read("*a")
    f:close()
    return s
end

local fails = 0
local function check(name, cond, extra)
    if cond then print("  OK   " .. name)
    else fails = fails + 1 print("  FAIL " .. name .. "   " .. tostring(extra or "")) end
end
local function has(src, n) return src:find(n, 1, true) ~= nil end

local core = read("lua/autorun/sh_grm_fire.lua")
local acc = read("lua/autorun/sh_grm_fire_access.lua")
local hose = read("addons/grm_fire/lua/weapons/weapon_grm_hose.lua")
local ext = read("addons/grm_fire/lua/weapons/weapon_extinguisher.lua")
local packHose = read("addons/grm_fire/lua/weapons/weapon_firehose.lua")

print("\n=== МОДЕЛИ _grm ===")
check("ствол GRM c_firehose_grm", has(hose, "c_firehose_grm.mdl"))
check("ствол GRM w_firehose_grm", has(hose, "w_firehose_grm.mdl"))
check("нет старого c_firehose.mdl в GRM SWEP", not hose:find("c_firehose.mdl", 1, true))
check("огнетушитель c_fire_extinguisher_grm", has(ext, "c_fire_extinguisher_grm.mdl"))
check("огнетушитель w_fire_extinguisher_grm", has(ext, "w_fire_extinguisher_grm.mdl"))
check("огнетушитель без оборванного if SERVER", not ext:find("if ( SERVER ) then --", 1, true))
check("огнетушитель без AddWorkshop", not has(ext, "AddWorkshop"))
check("пак-шланг c_firehose_grm", has(packHose, "c_firehose_grm.mdl"))
check("пак-шланг w_firehose_grm", has(packHose, "w_firehose_grm.mdl"))

print("\n=== СЕРВЕР Код 58 ===")
check("версия 1.4.1", has(core, 'F.Version = "1.4.1"'))
check("jsonT false,true", has(core, "util.JSONToTable, txt, false, true"))
check("карантин", has(core, ".corrupt."))
check("read-back", has(core, "SAVE read-back fail") or has(core, "chk ~= txt"))
check("массив incidents", has(core, "incidents"))
check("CreateVFire", has(core, "CreateVFire"))
check("рандом точек", has(core, "grm_fire_spot"))
check("плита", has(core, "grm_food_stove"))
check("CanFightPro", has(core, "function F.CanFightPro"))
check("хук CanHose", has(core, "GRM_FireAddon_CanHose"))
check("перм RegisterClass", has(core, "RegisterClass"))
check("нет принтера", not has(core, "grm_money_printer"))
check("нет пресса", not has(core, "grm_money_press"))

print("\n=== ACCESS ===")
check("jsonT access", has(acc, "util.JSONToTable, txt, false, true"))
check("/fire_access", has(acc, "/fire_access"))
check("/grm_fire_notify", has(acc, "/grm_fire_notify"))
check("вкладка «Пожарные» через хук меню (без подмены OpenAdminMenu)", has(acc, 'hook.Add("GRM_FactionsAdmin_BuildTabs", "GRM_FireAccess_Tab"') and not has(acc, "OpenAdminMenu = function"))
check("глобал не локализован как local OpenAdminMenu", not acc:find("local OpenAdminMenu", 1, true))
check("вкладка Пожарные", has(acc, "Пожарные"))
check("notify массив", has(acc, "factions = arr"))

local truck = read("lua/autorun/sh_grm_fire_truck.lua")
print("\n=== МАШИНА ===")
check("CommissionTruck", has(truck, "function F.CommissionTruck"))
check("DecommissionTruck", has(truck, "function F.DecommissionTruck"))
check("CanUseFireTruck", has(truck, "function F.CanUseFireTruck"))
check("IsListedFireTruck", has(truck, "function F.IsListedFireTruck"))
check("AttachPump", has(truck, "function F.AttachPump"))
check("/firetruck", has(truck, "/firetruck"))
check("/fire_trucks", has(truck, "/fire_trucks"))
check("PlayerSayTransform", has(truck, "PlayerSayTransform"))
check("trucks.json массив", has(truck, "trucks.json"))
check("jsonT trucks", has(truck, "util.JSONToTable, txt, false, true"))
check("карантин trucks", has(truck, ".corrupt."))
check("кнопка машин во вкладке", has(acc, "Пожарные машины"))

local addon = read("addons/grm_fire/lua/autorun/sh_grm_fire_addon.lua")
local hoseLua = read("addons/grm_fire/lua/autorun/sh_grm_fire_hose.lua")
local node = read("addons/grm_fire/lua/entities/grm_fire_hose_node/init.lua")
local pump = read("addons/grm_fire/lua/entities/grm_fire_pump/init.lua")
local tool = read("addons/grm_fire/lua/weapons/gmod_tool/stools/grm_fire_place.lua")
local qmenu = read("lua/autorun/sh_grm_qmenu.lua")
print("\n=== АДДОН 0.3 ===")
check("длина 2200", has(hoseLua, "MaxLength   = 2200") or has(hoseLua, "MaxLength = 2200"))
check("RewindAtSource", has(hoseLua, "function A.RewindAtSource"))
check("узлы без hunter cube", not has(node, "cube025x025x025"))
check("насос tpplugholder", has(pump, "tpplugholder_single"))
check("насос без SOLID_VPHYSICS", not has(pump, "SOLID_VPHYSICS"))
check("тул категория GRM", has(tool, 'TOOL.Category = "GRM"'))
check("тул не GRM Fire", not has(tool, 'TOOL.Category = "GRM Fire"'))
check("лестница в туле", has(tool, "grm_fire_ladder"))
check("лестница в каталоге Q", has(qmenu, "grm_fire_place"))
check("файл лестницы", (function()
    local f = io.open("addons/grm_fire/lua/entities/grm_fire_ladder/init.lua", "rb")
    if f then f:close() return true end
    return false
end)())

local pui = read("lua/autorun/sh_grm_fire_pump_ui.lua")
local ladW = read("addons/grm_fire/lua/weapons/weapon_grm_ladder.lua")
print("\n=== НАСОС G / ЛЕСТНИЦА ===")
check("панель OpenPumpPanel", has(pui, "function F.OpenPumpPanel"))
check("G KEY_G", has(pui, "KEY_G"))
check("баки foam powder", has(pui, "foam") and has(pui, "powder"))
check("закачка fill", has(pui, '"fill"'))
check("кнопка взять ствол", has(pui, '"take"'))
check("кнопка ВЗЯТЬ РУКАВ в меню", has(pui, "ВЗЯТЬ РУКАВ"))
check("кнопка Связать с гидрантом", has(pui, "Связать машину с гидрантом"))
check("act link", has(pui, 'act == "link"'))
check("LaySupplyLine", has(hoseLua, "function A.LaySupplyLine"))
check("клиент рисует кабели", has(hoseLua, "GRM_FireHose_Vis"))
check("путь по сети", has(hoseLua, "GRM_FireHose_Path"))
check("лента ColorMaterial", has(hoseLua, "SetColorMaterial"))
check("нет redcable в HoseCfg", not hoseLua:find('Material    = "cable/redcable"', 1, true))
check("TakeHoseFromTruck", has(truck, "function F.TakeHoseFromTruck"))
check("EnsureTruckPump", has(truck, "function F.EnsureTruckPump"))
check("чат /рукав", has(truck, '"/рукав"') or has(truck, "/рукав"))
check("узлы без альфы 0", not node:find("Color(255, 255, 255, 0)", 1, true))
check("файл материала рукава", (function()
    local f = io.open("addons/grm_fire/materials/grm/firehose.vmt", "rb")
    if f then f:close() return true end
    return false
end)())
check("инкассация G не по гидранту", (function()
    local inc = read("lua/autorun/sh_grm_incassation.lua")
    local a = inc:find("function getMyIncassCarClient", 1, true) or 0
    local b = inc:find("GRM_Incass_GKey", 1, true) or 0
    return a > 0 and b > 0 and a < b and inc:find("grm_fire_", 1, true) ~= nil
end)())
check("IsFireGContext общий", has(core, "function F.IsFireGContext"))
check("IsFireEnt общий", has(core, "function F.IsFireEnt"))
check("инкассация G зовёт IsFireGContext", (function()
    local inc = read("lua/autorun/sh_grm_incassation.lua")
    return inc:find("isFireGContextClient", 1, true) ~= nil
        and inc:find("if isFireGContext(ply) then return end", 1, true) ~= nil
        and inc:find("GRM_FireTruck", 1, true) ~= nil
end)())
check("G насоса не по дежурству вдали", not pui:find("if not nearPump and not IsValid(duty) then return end", 1, true))
check("G насоса через IsFireGContext", has(pui, "IsFireGContext"))
check("инкассация G без рейса молчит", (function()
    local inc = read("lua/autorun/sh_grm_incassation.lua")
    return inc:find("onIncass", 1, true) ~= nil
        and inc:find("без рейса и без чемодана", 1, true) ~= nil
        and inc:find("молчим: G у пожарки", 1, true) ~= nil
end)())
check("своя пожарка в контексте G", has(core, "GRM_FireMyTruck"))
check("укладка без SetNoDraw", not node:find("SetNoDraw(true)", 1, true))
check("лестница aluminium", has(ladW, "ladderaluminium.mdl"))
check("лестница ПКМ на машину", has(ladW, "AttachToVehicle"))
check("насос Consume agent", has(pump, "function ENT:Consume"))
check("нет автозаливки +25", not has(pump, "self:Fill(25)"))
check("SweepOrphanGear", has(core, "function F.SweepOrphanGear"))
check("не пермить бортовой насос", has(core, "GRM_Fire_NoTruckPerm"))
check("AttachPump без Placed", not truck:find("hook.Run(\"GRM_FireAddon_Placed\", pump", 1, true))
check("насос помечает TruckGear", has(pump, "GRM_TruckGear"))
local hoseInit = read("addons/grm_fire/lua/entities/grm_fire_hose/init.lua")
local hoseShared = read("addons/grm_fire/lua/entities/grm_fire_hose/shared.lua")
check("смотка серверная TryRewind", has(hoseInit, "function ENT:TryRewind"))
check("смотка IsWalkingBack", has(hoseInit, "function ENT:IsWalkingBack"))
check("смотка ReelIn ALT", has(hoseInit, "function ENT:ReelIn"))
check("нет узкого LayStep*1.25", not hoseInit:find("LayStep or 70) * 1.25", 1, true))
check("hint геометрии HoseMoveHint", has(hoseLua, "function A.HoseMoveHint"))
check("Think зовёт MoveHint", has(hoseInit, "self:MoveHint"))
check("S IN_BACK сматывает", has(hoseInit, "IN_BACK"))
check("не класть при ходе назад", has(hoseInit, 'hint == "lay"') or has(hoseInit, "not self:IsWalkingBack"))
check("FollowHost тянет за машиной", has(hoseInit, "function ENT:FollowHost"))
check("HoseDragPoint", has(hoseLua, "function A.HoseDragPoint"))
check("плоский шланг HoseBeamHalfH", has(hoseLua, "HoseBeamHalfH = 0.28"))
check("нет второго opaque-хука рукава", not hoseLua:find('PostDrawOpaqueRenderables", "GRM_FireHose_Vis"', 1, true))
check("LayStep 40", has(hoseLua, "LayStep     = 40") or has(hoseLua, "A.HoseCfg.LayStep = 40"))
check("livePts живые концы", has(hoseLua, "function livePts") or has(hoseLua, "local function livePts"))
check("спуск на землю dropGround", has(hoseLua, "dropGround"))
check("SrcPos NetworkVar", has(hoseShared, "SrcPos"))
check("SyncAnchors", has(hoseInit, "function ENT:SyncAnchors"))
check("InsertLayAt колышек", has(hoseInit, "function ENT:InsertLayAt"))
check("PayoutFromSource не натягивает", has(hoseInit, "function ENT:PayoutFromSource"))
check("DeployTo кладёт землю", has(hoseInit, "NODE_LAY") and has(hoseInit, "GroundSnap(origin)"))
check("ClearHosesOn", has(hoseLua, "function A.ClearHosesOn"))
check("HoseTouches", has(hoseLua, "function A.HoseTouches"))
check("насос OnRemove сматывает", has(pump, "function ENT:OnRemove") and has(pump, "ClearHosesOn"))
check("DropTruckGear", has(truck, "function F.DropTruckGear"))
check("рукав без источника сматывается", has(hoseInit, "not IsValid(src)") and has(hoseInit, "self:Rewind()"))
check("ClearOrphanHoses", has(hoseLua, "function A.ClearOrphanHoses"))
check("EntityRemoved без IsValid-барьера", has(truck, "looksLikeTruck") and not truck:find('if not IsValid(ent) then return end\n        local cls = ent:GetClass()', 1, true))

local spotInit = read("addons/grm_fire/lua/entities/grm_fire_spot/init.lua")
local spotCl = read("addons/grm_fire/lua/entities/grm_fire_spot/cl_init.lua")
local spots = read("lua/autorun/sh_grm_fire_spots.lua")
print("\n=== ТОЧКИ ОЧАГА ===")
check("точка без SetNoDraw", not spotInit:find("SetNoDraw(true)", 1, true))
check("точка без SetNotSolid", not spotInit:find("SetNotSolid(true)", 1, true))
check("точка IgniteSpot", has(spotInit, "function ENT:IgniteSpot"))
check("маркер GRM_FireSpot_Vis", has(spotCl, "GRM_FireSpot_Vis"))
check("тул ПКМ поджигает", has(tool, "IgniteSpot"))
check("тул ищет точку рядом", has(tool, "findFireTarget"))
check("вес/метка cvar", has(tool, "grm_fire_place_weight") and has(tool, "grm_fire_place_label"))
check("схема Q вес точки", has(qmenu, "grm_fire_place_weight"))
check("панель /fire_spots", has(spots, "/fire_spots"))
check("конфиг LoadConfig", has(core, "function F.LoadConfig"))
check("конфиг SaveConfig", has(core, "function F.SaveConfig"))
check("RescheduleRandom", has(core, "F.RescheduleRandom"))
check("кнопка очагов во вкладке", has(acc, "Очаги и таймеры"))
local status = read("lua/autorun/sh_grm_fire_status.lua")
check("учёт NoteFight", has(status, "function F.NoteFight"))
check("уведомление локализован", has(status, "Пожар локализован"))
check("уведомление потушен", has(status, "Пожар потушен"))
check("журнал log.json", has(status, "grm_fire/log.json"))
check("MarkExtinguished", has(status, "function F.MarkExtinguished"))
check("NotifyFactions цвет", has(acc, "function F.NotifyFactions(text, pos, r, g, b)"))
check("статус v1.5.0 (диспетчеризация вызовов)", has(status, "StatusVersion = \"1.5.0\"") and has(status, "GRM_FireIncidentOpened"))
check("BuildFromExisting скан", has(status, "function F.BuildFromExisting"))
check("пик min 1", has(status, "math.max(inc.peak or 0, 1)") or has(status, "peak = 1"))
check("мягкий локализован 2.5с", has(status, "2.5"))
check("оба события потушен+локализован", has(status, "MarkLocalized(inc)") and has(status, "fought") and has(status, "localized"))
check("Notify чат дубль", has(status, "ChatPrint"))
check("рядом 1500", has(status, "1500"))
check("бойцы в Notify", has(status, "fighters"))
check("журнал /fire_log чат", has(status, "/fire_log") and has(status, "журнал_пожаров"))
check("лог net Req/Data", has(status, "GRM_FireLog_Req") and has(status, "GRM_FireLog_Data"))
check("клиент OpenLogPanel", has(status, "function GRM.Fire.OpenLogPanel") or has(status, "OpenLogPanel"))
check("CanFightPro в Notify", has(status, "CanFightPro") and has(status, "CanDispatch"))

print("")
if fails == 0 then print("ВСЕ ТЕСТЫ ПРОЙДЕНЫ (fire)")
else print("ПРОВАЛОВ: " .. fails) end
print(("FIRE failures=%d"):format(fails))
os.exit(fails == 0 and 0 or 1)
