-- Faction Core v4: stable department labels and personnel contracts.
local function read(p)local f=assert(io.open(p,"rb"));local s=f:read("*a");f:close();return s end
local fac=read("lua/autorun/sh_factions.lua");local core=read("lua/autorun/sh_grm_factions_core_v4.lua");local personnel=read("lua/autorun/sh_grm_faction_personnel.lua");local fixes=read("lua/autorun/sh_faction_fixes.lua")
local fail,n=0,0;local function ok(v,msg)n=n+1;if v then print("  ok  "..msg)else fail=fail+1;print("  FAIL "..msg)end end
ok(fac:find("function GRM.Factions.DepartmentDisplayName",1,true),"department display resolver exists")
ok(fac:find("f.DepartmentDisplayNames=",1,true)and fac:find("DepartmentDisplayNames=f.DepartmentDisplayNames",1,true),"department labels persist and sync")
local ra=assert(fac:find("local function renameDepartment",1,true));local rb=assert(fac:find("local function moveDepartment",ra,true));local rename=fac:sub(ra,rb-1)
ok(rename:find("DepartmentDisplayNames",1,true)and not rename:find("f.Departments[i]",1,true),"rename changes only display metadata")
ok(not rename:find("info.Department",1,true),"rename never rewrites member department")
ok(not rename:find("f.DepartmentModels",1,true)and not rename:find("f.DepartmentWeapons",1,true),"rename never touches model/weapon settings")
ok(fac:find("Системный ключ:",1,true)and fac:find("Настройки и участники останутся привязаны",1,true),"department UI explains stable key")
ok((core:match('C%.Version="(%d+)') or "0")+0>=4 and core:find("function C.Touch",1,true),"Faction Core revision/event facade exists (>=v4)")
ok(core:find("normalizePersonnel",1,true)and core:find("C.MaxHistory=200",1,true),"personnel records are normalized and bounded")
ok(core:find("PersonnelArchive",1,true)and core:find("member.removed",1,true),"dismissed personnel files are archived")
ok(core:find("GRM_FactionMemberJoined",1,true)and core:find("GRM_FactionMemberRoleChanged",1,true)and core:find("GRM_FactionMemberDepartmentChanged",1,true),"membership mutations feed personnel history")
ok(core:find("GRM_FactionDutyChanged",1,true),"duty changes feed personnel history")
ok(fac:find('hook.Run("GRM_FactionMemberJoined"',1,true)and fac:find('hook.Run("GRM_FactionMemberRemoved"',1,true),"legacy faction mutations emit Core events")
ok(personnel:find('tabs:AddSheet("Кадровые дела"',1,true),"unified faction menus receive personnel tab")
ok(personnel:find("ДОБАВИТЬ ЗАПИСЬ",1,true)and personnel:find("БЛАГОДАРНОСТЬ",1,true)and personnel:find("ВЗЫСКАНИЕ",1,true),"personnel UI has practical actions")
ok(personnel:find('faction.personnel.request',1,true)and personnel:find('faction.personnel.action',1,true),"personnel network is guarded")
ok(personnel:find("SetProbation",1,true)and personnel:find("ИСПЫТАТЕЛЬНЫЙ СРОК",1,true),"probation workflow exists")
ok(personnel:find("sendList",1,true)and personnel:find('r.archived and "АРХИВ"',1,true),"personnel UI includes dismissed archive")
ok(fixes:find("DepartmentModels",1,true)and fixes:find("DepartmentWeapons",1,true),"legacy department equipment maps remain intact")
print(("FACTION CORE V4: %d/%d failures=%d"):format(n-fail,n,fail));os.exit(fail==0 and 0 or 1)
