"""MDL — скомпилированная модель Source (studiomdl v44–v49) и спутники.

Разбираем то, что нужно при интеграции чужой модели в аддон:

* заголовок: версия, внутреннее имя, чек-сумма, флаги, габариты, масса-хабар;
* кости (имена, родители) — нужно для аттачментов и анимаций;
* секвенции (имена) — что модель вообще умеет играть;
* бодипарты и их модели/меши — сколько «тел» и скинов;
* текстуры + cdmaterials — ГЛАВНОЕ: из них собирается список путей
  materials/..., без которых модель будет фиолетовой;
* аттачменты — точки крепления (для телефона в руке, флешки в терминале);
* includemodels — внешние наборы анимаций, которые модель тянет за собой;
* спутники: .vvd (вершины/LOD), .vtx (полосы для рендера), .phy (масса,
  surfaceprop, число солидов).

Разбор защитный: любая непонятная секция даёт пустой список и запись в
`warnings`, чтобы отчёт по чужому паку не падал на первой битой модели.
"""

from __future__ import annotations

import io
import os
import struct
from typing import Dict, List, Optional, Tuple

STUDIO_IDENT = b"IDST"
ANIM_IDENT = b"IDAG"

# Флаги studiohdr (только осмысленные для нас).
STUDIOHDR_FLAGS = {
    1 << 0: "AUTOGENERATED_HITBOX",
    1 << 1: "USES_ENV_CUBEMAP",
    1 << 2: "FORCE_OPAQUE",
    1 << 3: "TRANSLUCENT_TWOPASS",
    1 << 4: "STATIC_PROP",
    1 << 6: "HAS_SHADOW_LOD",
    1 << 8: "USE_SHADOWLOD_MATERIALS",
    1 << 9: "OBSOLETE",
    1 << 11: "NO_FORCED_FADE",
    1 << 12: "FORCE_PHONEME_CROSSFADE",
    1 << 13: "CONSTANT_DIRECTIONAL_LIGHT_DOT",
    1 << 14: "FLEXES_CONVERTED",
    1 << 15: "BUILT_IN_PREVIEW_MODE",
    1 << 17: "AMBIENT_BOOST",
    1 << 18: "DO_NOT_CAST_SHADOWS",
    1 << 19: "CAST_TEXTURE_SHADOWS",
}

BONE_STRIDE = 216
TEXTURE_STRIDE = 64
BODYPART_STRIDE = 16
MODEL_STRIDE = 148
ATTACHMENT_STRIDE = 92
SEQDESC_STRIDE = 212
MODELGROUP_STRIDE = 8


def _cstr(data: bytes, offset: int, limit: int = 512) -> str:
    if offset <= 0 or offset >= len(data):
        return ""
    stop = data.find(b"\x00", offset, min(len(data), offset + limit))
    if stop < 0:
        stop = min(len(data), offset + limit)
    return data[offset:stop].decode("ascii", "replace")


class Bone:
    __slots__ = ("index", "name", "parent", "pos", "surfaceprop")

    def __init__(self, index, name, parent, pos, surfaceprop):
        self.index, self.name, self.parent = index, name, parent
        self.pos, self.surfaceprop = pos, surfaceprop


class Sequence:
    __slots__ = ("index", "name", "activity")

    def __init__(self, index, name, activity):
        self.index, self.name, self.activity = index, name, activity


class BodyPart:
    __slots__ = ("index", "name", "models")

    def __init__(self, index, name, models):
        self.index, self.name, self.models = index, name, models


class SubModel:
    __slots__ = ("name", "num_meshes", "num_vertices")

    def __init__(self, name, num_meshes, num_vertices):
        self.name, self.num_meshes, self.num_vertices = name, num_meshes, num_vertices


class Attachment:
    __slots__ = ("index", "name", "bone")

    def __init__(self, index, name, bone):
        self.index, self.name, self.bone = index, name, bone


class MDL:
    """Читатель studiomdl-заголовка и его таблиц."""

    def __init__(self, data: bytes, path: str = "<memory>"):
        self.path = path
        self.data = data
        self.warnings: List[str] = []
        if len(data) < 408 or data[:4] not in (STUDIO_IDENT, ANIM_IDENT):
            raise ValueError(f"не MDL: сигнатура {data[:4]!r}")
        d = data
        self.ident = d[:4].decode("ascii")
        (self.version, self.checksum) = struct.unpack_from("<ii", d, 4)
        self.internal_name = _cstr(d, 12, 64)
        (self.data_length,) = struct.unpack_from("<i", d, 76)
        self.eye_position = struct.unpack_from("<3f", d, 80)
        self.illum_position = struct.unpack_from("<3f", d, 92)
        self.hull_min = struct.unpack_from("<3f", d, 104)
        self.hull_max = struct.unpack_from("<3f", d, 116)
        self.view_bbmin = struct.unpack_from("<3f", d, 128)
        self.view_bbmax = struct.unpack_from("<3f", d, 140)
        (self.flags,) = struct.unpack_from("<i", d, 152)
        (self.bone_count, self.bone_offset) = struct.unpack_from("<ii", d, 156)
        (self.bonectrl_count, self.bonectrl_offset) = struct.unpack_from("<ii", d, 164)
        (self.hitbox_count, self.hitbox_offset) = struct.unpack_from("<ii", d, 172)
        (self.localanim_count, self.localanim_offset) = struct.unpack_from("<ii", d, 180)
        (self.localseq_count, self.localseq_offset) = struct.unpack_from("<ii", d, 188)
        (self.activity_list_version, self.events_indexed) = struct.unpack_from("<ii", d, 196)
        (self.texture_count, self.texture_offset) = struct.unpack_from("<ii", d, 204)
        (self.texturedir_count, self.texturedir_offset) = struct.unpack_from("<ii", d, 212)
        (self.skinref_count, self.skinfamily_count, self.skinref_offset) = struct.unpack_from("<3i", d, 220)
        (self.bodypart_count, self.bodypart_offset) = struct.unpack_from("<ii", d, 232)
        (self.attachment_count, self.attachment_offset) = struct.unpack_from("<ii", d, 240)
        # Хвост studiohdr_t легко «сдвинуть на одно поле»: после аттачментов
        # идут localnodes (ТРИ поля: count/index/nameindex), flexdesc,
        # flexcontrollers, flexrules, ikchains, mouths, poseparams,
        # surfaceprop, keyvalues, ikautoplaylocks — и только потом масса.
        # Смещения сверены на реальных моделях: mass=328 совпадает с массой
        # из .phy, contents=332, includemodels=336/340.
        (self.surfaceprop_offset,) = struct.unpack_from("<i", d, 308)
        (self.mass,) = struct.unpack_from("<f", d, 328)
        (self.contents,) = struct.unpack_from("<i", d, 332)
        (self.includemodel_count, self.includemodel_offset) = struct.unpack_from("<ii", d, 336)
        self.surfaceprop = _cstr(d, self.surfaceprop_offset)

    # ── загрузка ──────────────────────────────────────────────────────
    @classmethod
    def open(cls, path: str) -> "MDL":
        with io.open(path, "rb") as fh:
            return cls(fh.read(), path)

    @property
    def flag_names(self) -> List[str]:
        return [name for bit, name in STUDIOHDR_FLAGS.items() if self.flags & bit]

    @property
    def is_static_prop(self) -> bool:
        return bool(self.flags & (1 << 4))

    # ── таблицы ───────────────────────────────────────────────────────
    def bones(self) -> List[Bone]:
        out: List[Bone] = []
        try:
            for i in range(min(self.bone_count, 4096)):
                base = self.bone_offset + i * BONE_STRIDE
                if base + BONE_STRIDE > len(self.data):
                    break
                name_off, parent = struct.unpack_from("<ii", self.data, base)
                pos = struct.unpack_from("<3f", self.data, base + 32)
                surf_off = struct.unpack_from("<i", self.data, base + 208)[0]
                out.append(Bone(i, _cstr(self.data, base + name_off), parent, pos,
                                _cstr(self.data, base + surf_off) if surf_off else ""))
        except Exception as exc:  # noqa: BLE001
            self.warnings.append(f"кости не разобраны: {exc}")
        return out

    def sequences(self) -> List[Sequence]:
        out: List[Sequence] = []
        try:
            for i in range(min(self.localseq_count, 4096)):
                base = self.localseq_offset + i * SEQDESC_STRIDE
                if base + 16 > len(self.data):
                    break
                label_off, act_off = struct.unpack_from("<ii", self.data, base + 4)
                out.append(Sequence(i, _cstr(self.data, base + label_off),
                                    _cstr(self.data, base + act_off) if act_off else ""))
        except Exception as exc:  # noqa: BLE001
            self.warnings.append(f"секвенции не разобраны: {exc}")
        return out

    def texture_names(self) -> List[str]:
        out: List[str] = []
        try:
            for i in range(min(self.texture_count, 1024)):
                base = self.texture_offset + i * TEXTURE_STRIDE
                if base + 8 > len(self.data):
                    break
                name_off = struct.unpack_from("<i", self.data, base)[0]
                out.append(_cstr(self.data, base + name_off))
        except Exception as exc:  # noqa: BLE001
            self.warnings.append(f"текстуры не разобраны: {exc}")
        return out

    def cdmaterials(self) -> List[str]:
        out: List[str] = []
        try:
            for i in range(min(self.texturedir_count, 64)):
                off = struct.unpack_from("<i", self.data, self.texturedir_offset + i * 4)[0]
                path = _cstr(self.data, off).replace("\\", "/")
                if path:
                    out.append(path if path.endswith("/") else path + "/")
        except Exception as exc:  # noqa: BLE001
            self.warnings.append(f"cdmaterials не разобраны: {exc}")
        return out

    def material_paths(self) -> List[str]:
        """Полные пути materials/<cdmaterial><texture>.vmt (все комбинации).

        Движок ищет текстуру в каждой из cdmaterials-папок по очереди, так
        что достаточно, чтобы существовал ОДИН вариант из списка.
        """
        cds = self.cdmaterials() or [""]
        out = []
        for tex in self.texture_names():
            tex_norm = tex.replace("\\", "/").lstrip("/")
            for cd in cds:
                out.append(f"materials/{cd}{tex_norm}.vmt".replace("//", "/"))
        return out

    def bodyparts(self) -> List[BodyPart]:
        out: List[BodyPart] = []
        try:
            for i in range(min(self.bodypart_count, 512)):
                base = self.bodypart_offset + i * BODYPART_STRIDE
                if base + BODYPART_STRIDE > len(self.data):
                    break
                name_off, num_models, _base_idx, model_off = struct.unpack_from("<4i", self.data, base)
                models = []
                for m in range(min(num_models, 256)):
                    mb = base + model_off + m * MODEL_STRIDE
                    if mb + 76 > len(self.data):
                        break
                    mname = _cstr(self.data, mb, 64)
                    num_meshes = struct.unpack_from("<i", self.data, mb + 72)[0]
                    num_verts = struct.unpack_from("<i", self.data, mb + 80)[0]
                    models.append(SubModel(mname, num_meshes, num_verts))
                out.append(BodyPart(i, _cstr(self.data, base + name_off), models))
        except Exception as exc:  # noqa: BLE001
            self.warnings.append(f"бодипарты не разобраны: {exc}")
        return out

    def attachments(self) -> List[Attachment]:
        out: List[Attachment] = []
        try:
            for i in range(min(self.attachment_count, 512)):
                base = self.attachment_offset + i * ATTACHMENT_STRIDE
                if base + 12 > len(self.data):
                    break
                name_off, _flags, bone = struct.unpack_from("<3i", self.data, base)
                out.append(Attachment(i, _cstr(self.data, base + name_off), bone))
        except Exception as exc:  # noqa: BLE001
            self.warnings.append(f"аттачменты не разобраны: {exc}")
        return out

    def includemodels(self) -> List[str]:
        out: List[str] = []
        try:
            for i in range(min(self.includemodel_count, 256)):
                base = self.includemodel_offset + i * MODELGROUP_STRIDE
                if base + 8 > len(self.data):
                    break
                label_off, name_off = struct.unpack_from("<ii", self.data, base)
                name = _cstr(self.data, base + name_off) if name_off else ""
                if name:
                    out.append(name.replace("\\", "/"))
        except Exception as exc:  # noqa: BLE001
            self.warnings.append(f"includemodels не разобраны: {exc}")
        return out

    def skins(self) -> List[List[int]]:
        """Матрица скинов: строка = семейство, столбец = ссылка на текстуру."""
        out: List[List[int]] = []
        try:
            for fam in range(min(self.skinfamily_count, 256)):
                row = []
                for ref in range(min(self.skinref_count, 256)):
                    pos = self.skinref_offset + (fam * self.skinref_count + ref) * 2
                    if pos + 2 > len(self.data):
                        break
                    row.append(struct.unpack_from("<h", self.data, pos)[0])
                out.append(row)
        except Exception as exc:  # noqa: BLE001
            self.warnings.append(f"скины не разобраны: {exc}")
        return out

    # ── спутники ──────────────────────────────────────────────────────
    def sibling(self, ext: str) -> Optional[str]:
        stem = os.path.splitext(self.path)[0]
        for candidate in (stem + ext, stem + ext.upper()):
            if os.path.isfile(candidate):
                return candidate
        if ext == ".vtx":  # у vtx имя бывает с уровнем dx
            for suffix in (".dx90.vtx", ".dx80.vtx", ".sw.vtx"):
                if os.path.isfile(stem + suffix):
                    return stem + suffix
        return None

    def companions(self) -> Dict[str, Optional[dict]]:
        return {
            "vvd": read_vvd(self.sibling(".vvd")),
            "vtx": read_vtx(self.sibling(".vtx")),
            "phy": read_phy(self.sibling(".phy")),
        }

    # ── сводка ────────────────────────────────────────────────────────
    def summary(self, with_companions: bool = True) -> dict:
        bodyparts = self.bodyparts()
        info = {
            "path": self.path,
            "internal_name": self.internal_name,
            "version": self.version,
            "checksum": self.checksum,
            "size_bytes": len(self.data),
            "flags": self.flags,
            "flag_names": self.flag_names,
            "static_prop": self.is_static_prop,
            "mass": round(self.mass, 3),
            "surfaceprop": self.surfaceprop,
            "bones": self.bone_count,
            "sequences": self.localseq_count,
            "animations": self.localanim_count,
            "hitboxes": self.hitbox_count,
            "attachments": self.attachment_count,
            "bodyparts": len(bodyparts),
            "submodels": sum(len(bp.models) for bp in bodyparts),
            "vertices": sum(m.num_vertices for bp in bodyparts for m in bp.models),
            "textures": self.texture_names(),
            "cdmaterials": self.cdmaterials(),
            "skin_families": self.skinfamily_count,
            "includemodels": self.includemodels(),
            "hull_min": [round(v, 2) for v in self.hull_min],
            "hull_max": [round(v, 2) for v in self.hull_max],
            "warnings": self.warnings,
        }
        if with_companions:
            info["companions"] = self.companions()
        return info


# ── .vvd / .vtx / .phy ────────────────────────────────────────────────
def read_vvd(path: Optional[str]) -> Optional[dict]:
    if not path or not os.path.isfile(path):
        return None
    with io.open(path, "rb") as fh:
        d = fh.read(64)
    if len(d) < 64 or d[:4] != b"IDSV":
        return {"path": path, "error": "не VVD"}
    version, checksum, num_lods = struct.unpack_from("<3i", d, 4)
    lod_verts = list(struct.unpack_from("<8i", d, 16))
    num_fixups, fixup_start, vert_start, tangent_start = struct.unpack_from("<4i", d, 48)
    return {
        "path": path, "version": version, "checksum": checksum,
        "lods": num_lods, "lod_vertices": lod_verts[:max(1, num_lods)],
        "fixups": num_fixups, "vertex_data_start": vert_start,
        "tangent_data_start": tangent_start,
        "size_bytes": os.path.getsize(path),
    }


def read_vtx(path: Optional[str]) -> Optional[dict]:
    if not path or not os.path.isfile(path):
        return None
    with io.open(path, "rb") as fh:
        d = fh.read(36)
    if len(d) < 36:
        return {"path": path, "error": "усечённый VTX"}
    version, vert_cache = struct.unpack_from("<2i", d, 0)
    max_bones_strip, max_bones_tri = struct.unpack_from("<2H", d, 8)
    max_bones_vert, checksum, num_lods = struct.unpack_from("<3i", d, 12)
    _mat_replace_off, num_bodyparts = struct.unpack_from("<2i", d, 24)
    return {
        "path": path, "version": version, "checksum": checksum,
        "lods": num_lods, "bodyparts": num_bodyparts,
        "max_bones_per_vert": max_bones_vert,
        "max_bones_per_tri": max_bones_tri,
        "max_bones_per_strip": max_bones_strip,
        "vertex_cache_size": vert_cache,
        "size_bytes": os.path.getsize(path),
    }


def read_phy(path: Optional[str]) -> Optional[dict]:
    """Заголовок .phy + текстовый блок (там масса и surfaceprop)."""
    if not path or not os.path.isfile(path):
        return None
    with io.open(path, "rb") as fh:
        d = fh.read()
    if len(d) < 16:
        return {"path": path, "error": "усечённый PHY"}
    header_size, phy_id, solid_count, checksum = struct.unpack_from("<4i", d, 0)
    info = {
        "path": path, "id": phy_id, "solids": solid_count, "checksum": checksum,
        "size_bytes": len(d),
    }
    # Текстовая секция идёт после солидов; ищем её по характерному ключу.
    tail_at = d.find(b"solid {")
    if tail_at < 0:
        tail_at = d.find(b'"solid"')
    if tail_at >= 0:
        text = d[tail_at:].split(b"\x00", 1)[0].decode("ascii", "replace")
        info["text_section"] = text
        for key in ("mass", "surfaceprop", "name"):
            marker = f'"{key}"'
            pos = text.find(marker)
            if pos >= 0:
                rest = text[pos + len(marker):].strip()
                if rest.startswith('"'):
                    info[key] = rest[1:rest.find('"', 1)] if rest.find('"', 1) > 0 else ""
                else:
                    info[key] = rest.split()[0] if rest.split() else ""
    return info


def scan_models(root: str) -> List[str]:
    """Все .mdl в дереве (для пакетного аудита пака моделей)."""
    out = []
    for base, _dirs, files in os.walk(root):
        for fname in files:
            if fname.lower().endswith(".mdl"):
                out.append(os.path.join(base, fname))
    return sorted(out)
